# Generated by Django 2.0.6 on 2019-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=20, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': ('用户登录表',),
                'verbose_name_plural': ('用户登录表',),
                'db_table': 'login_user',
                'ordering': ['-user_id'],
            },
        ),
    ]
